{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/server-time": {
      "get": {
        "tags": [
          "test-controller"
        ],
        "operationId": "getCurrentServerTime",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/DateDto"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "DateDto": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}