name: Run Build on PRs

on: pull_request

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
